{{- if .Values.loom.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loom.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loom.labels" . | nindent 4 }}
  {{- with .Values.loom.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
